spring.application.name=fantaschedina

# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/fantaschedina
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# App
app.base-url=http://localhost:8080
app.mail.from=noreply@fantaschedina.dev

# Mail
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# Thymeleaf
spring.thymeleaf.cache=false
